server:
  port: 8084

spring:
  application:
    name: test

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/project_management
    username: postgres
    password: subhanalloh7777alhamdulillah&&

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        dialect: debug
